[float]
AsciiDoc image:https://travis-ci.com/asciidoc/asciidoc-py3.svg?branch=master["Build Status", link="https://travis-ci.com/asciidoc/asciidoc-py3"]
===================================================================================================================================

AsciiDoc is a text document format for writing notes, documentation,
articles, books, ebooks, slideshows, web pages, man pages and blogs.
AsciiDoc files can be translated to many formats including HTML, PDF,
EPUB, man page.

AsciiDoc is highly configurable: both the AsciiDoc source file syntax
and the backend output markups (which can be almost any type of
SGML/XML markup) can be customized and extended by the user.

Prerequisites
-------------
AsciiDoc is written in Python so you need a Python interpreter
(version 3.5 or later) to execute asciidoc(1). Python is installed by
default in most Linux distributions.  You can download Python from the
official Python website http://www.python.org.


Obtaining AsciiDoc
------------------
AsciiDoc's Python 3 port is currently under development. To obtain AsciiDoc,
download a copy of the repo from the GitHub project at
https://github.com/asciidoc/asciidoc-py3 and follow the instructions in
INSTALL.txt to build and install it.

Tools
-----
Current AsciiDoc version tested on Ubuntu 18.04 with:

- Python 3.6.5
- DocBook XSL Stylesheets 1.76.1
- xsltproc (libxml 20706, libxslt 10126 and libexslt 815).
- w3m 0.5.2
- dblatex 0.3
- FOP 0.95
- A-A-P 1.091


Copying
-------
Copyright (C) 2002-2013 Stuart Rackham. Free use of this software is
granted under the terms of the GNU General Public License version 2
(GPLv2).
